/**
 * API functions for fetching data from various sources
 */

import { delay, getCachedResponse, setCachedResponse, apiRequestQueue, processQueue } from './cache.js';

// Retry function with exponential backoff
export async function fetchWithRetry(url, options = {}, maxRetries = 3) {
  let retries = 0;
  let lastError;

  // Add CORS proxy for ArXiv API requests if needed
  if (
    url.startsWith("https://export.arxiv.org") &&
    !url.startsWith("https://")
  ) {
    // Use HTTPS instead of HTTP
    url = url.replace("http://", "https://");
    console.log(`Converted ArXiv API URL to HTTPS: ${url}`);
  }

  while (retries < maxRetries) {
    try {
      console.log(`Fetching ${url} (attempt ${retries + 1}/${maxRetries})`);
      const response = await fetch(url, options);

      // If it's a rate limit error, retry with exponential backoff
      if (response.status === 429) {
        const isSemanticScholar = url.includes('semanticscholar.org');

        if (retries === 0 && isSemanticScholar) {
          alert("Alice has hit the Semantic Scholar API rate limit. Please wait while we retry...");
        }

        let waitTime;
        const retryAfterHeader = response.headers.get("Retry-After");

        if (retryAfterHeader) {
          // If server provides retry-after header, use it
          waitTime = parseInt(retryAfterHeader, 10) * 1000;
        } else {
          // Use exponential backoff with longer initial wait for Semantic Scholar
          const baseWait = isSemanticScholar ? 5000 : 1000; // 5 seconds for S2, 1 second for others
          waitTime = baseWait * Math.pow(2, retries);
        }

        // Cap the wait time at 60 seconds
        waitTime = Math.min(waitTime, 60000);

        console.log(`Rate limited (429). Retrying after ${waitTime}ms...`);
        await delay(waitTime);
        retries++;
        continue;
      }

      if (!response.ok) {
        throw new Error(`API responded with status ${response.status}`);
      }

      // Success - clear any rate limit alerts for subsequent requests
      return response;
    } catch (error) {
      lastError = error;

      // Log more details about the error
      console.error(`Fetch error (attempt ${retries + 1}/${maxRetries}):`, {
        url,
        errorMessage: error.message,
        errorType: error.name,
      });

      if (retries === maxRetries - 1) {
        break;
      }

      // Wait with exponential backoff before retrying for other errors
      const waitTime = Math.pow(2, retries) * 1000;
      console.log(`Error fetching. Retrying after ${waitTime}ms...`, error);
      await delay(waitTime);
      retries++;
    }
  }

  // If we've exhausted all retries, throw the last error
  throw lastError;
}

export async function queuedFetch(url, options = {}, maxRetries = 3) {
  // Check cache first
  const cachedResponse = getCachedResponse(url, options);
  if (cachedResponse) {
    return cachedResponse;
  }

  const apiType = url.includes('semanticscholar.org') ? 'semanticScholar' :
                  url.includes('arxiv.org') ? 'arxiv' : 'other';

  if (apiType === 'other') {
    // For non-rate-limited APIs, proceed directly
    const response = await fetchWithRetry(url, options, maxRetries);
    setCachedResponse(url, options, response);
    return response;
  }

  return new Promise((resolve, reject) => {
    apiRequestQueue[apiType].push({ url, options, maxRetries, resolve, reject });
    processQueue(apiType);
  });
}

// Helper function to fetch BibTex data from API
export async function fetchBibTexData(arxivId) {
  try {
    const bibtexUrl = `https://api.aryankeluskar.com/api/bibtex?arxiv_id=${arxivId}`;
    const response = await fetchWithRetry(bibtexUrl, {}, 3);
    return await response.text();
  } catch (error) {
    console.error("Error fetching BibTex data:", error);
    throw error;
  }
}

// Function to post content to online clipboard
export async function postToOnlineClipboard(content, title) {
  console.log("Posting paper implementation to online clipboard...");

  try {
    // Format the content with a title and metadata
    const formattedContent = `# Implementation Guide for: ${title}\n\n${content}\n\n---\nGenerated by ArXiv Viewer Extension using Claude AI`;

    // Post to the online clipboard service
    const response = await fetch("https://online-clipboard-two.vercel.app/", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ content: formattedContent }),
    });

    if (!response.ok) {
      throw new Error(
        `Failed to post to clipboard: ${response.status} ${response.statusText}`
      );
    }

    const result = await response.json();
    console.log("Successfully posted to online clipboard:", result);
    return result;
  } catch (error) {
    console.error("Error posting to online clipboard:", error);
    throw error;
  }
}

// Helper functions for code generation
export async function fetchPaperText(arxivLink) {
  console.log("Fetching paper text from arXiv link:", arxivLink);

  try {
    // Extract the arXiv ID from the link
    const arxivIdMatch = arxivLink.match(/abs\/([^\/]+)/);
    if (!arxivIdMatch || !arxivIdMatch[1]) {
      throw new Error("Could not extract arXiv ID from link");
    }

    const arxivId = arxivIdMatch[1];
    console.log("Extracted arXiv ID:", arxivId);

    // Use ArXiv API to get paper details
    const apiEndpoint = `https://export.arxiv.org/api/query?id_list=${arxivId}`;
    const apiResponse = await fetchWithRetry(apiEndpoint, {}, 2);

    const xmlData = await apiResponse.text();
    const parser = new DOMParser();
    const xmlDoc = parser.parseFromString(xmlData, "text/xml");

    // Extract summary and other details
    const summary = xmlDoc.querySelector("summary")?.textContent || "";
    const title = xmlDoc.querySelector("title")?.textContent || "";
    const authors = Array.from(xmlDoc.querySelectorAll("author name"))
      .map(el => el.textContent)
      .join(", ");

    // Combine the data
    return `Title: ${title}\nAuthors: ${authors}\n\nAbstract: ${summary}`;
  } catch (error) {
    console.error("Error fetching paper text:", error);
    throw new Error(`Failed to fetch paper text: ${error.message}`);
  }
}
